[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "24"

[[headers]]
  for = "/service-worker2.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/firebase-messaging-sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
